### PR TITLE
(GH-212) Update Internet Setup doc

### PR DESCRIPTION
**Pull request by vexx32**
While it's more informational than anything else for QDEv2 it is likely still handy to have for debugging efforts and other purposes, so I've gone through and made some edits that hopefully help it make a little more sense. I added a banner to the top indicating it's mainly informational for v2 onward, and tidied up a few things I saw as I read through it.

I also adjusted certain elements to bring it more in line with the format of the v2 docs and removed the version suffix from the name.

Github apparently doesn't notice the rename and is treating it as a delete+add, but if you look at just the first commit you'll see the proper diff between the old and new docs.

### CODE REVIEW

**Review by adilio — APPROVED** [review]
This all LGTM! Basically the original content, so I'm good with it. I like how you hid the gifs in drop-down menus, nice touch. As long as you know how to organize the 2 versions separately, I think we're good.

**Comment by gep13** [comment]
@vexx32 @adilio are there any other changes required, in terms of routes to get this appearing on chocolatey.org correctly?  If not, I can get this merged in and pushed out.

**Comment by vexx32** [comment]
@gep13 since I removed the `-v1` suffix from the filename, we may need to update sidebar links if we had one for this doc. Actually, that reminds me, I'd better verify any links pointing to this doc are still linking to the right place. Will check that momentarily.

**Comment by gep13** [comment]
@vexx32 assuming that you are talking about the following:

image

That would be something that @designxsteph can help with to get a new entry in there.

I would say that having an entry here makes sense.

**Comment by gep13** [comment]
Wait, there is an entry in there:

image

But I think this is now in the wrong section, and should be moved up to the top section, right?

**Comment by designxsteph** [comment]
I can get a quick PR in to fix the navigation links (remove the `-v1` and move this doc out of the v1 dropdown)!

**Comment by designxsteph** [comment]
https://github.com/chocolatey/chocolatey.org/pull/969

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@vexx32 thanks for pulling this together

**Pull request merged**
