### PR TITLE
Clean up formatting in Home.md

### PR DESCRIPTION
**Pull request by i-give-up**
Add line breaks to Home/Forum/Twitter link.

Convert absolute links to internal reference links (`[[ ]]`)

### CODE REVIEW

**Comment by gep13** [comment]
@Redsandro did you also push this to the upstream wiki as well?

**Comment by Redsandro** [comment]
Upstream? The wiki is more complex than I thought.
I'm afraid not. I just checked, approved, and merged.

**Comment by gep13** [comment]
@Redsandro yeah, allowing collaboration on a GitHub wiki really isn't as easy as it should be.  What we have done is create this repo which has an upstream remote which is the actual GitHub Wiki for Chocolatey.  Any commits into this repo won't show up in the actual wiki until merged upstream.  It is a real drawback on the usage of the wiki :-(

**Comment by Redsandro** [comment]
@gep13  Did you push it then? 

It seems to be live here: https://github.com/chocolatey/choco/wiki

**Comment by gep13** [comment]
@Redsandro I am going to be honest, and say no.  Keeping these two things in sync is a little out of my git fu range.  The problem being that there will have been changed in the upstream repo that won't be in this one, and vice versa, and I am not confident in making the necessary changes.  I am hoping @ferventcoder will come along and explain the best process for doing this, and then I will be able to use that going forward :smile_cat:

**Comment by Redsandro** [comment]
Thanks for the info. I thought I'd ease the workload by verifying and merging something simple. But nothing is simple these days :fearful:

**Pull request merged**
