### PR TITLE
(GH-106) Remove rawgit recommendations

### LINKED ISSUE #106: Stop recommending rawgit
Considering that rawgit will be shutting down next year, and since they no longer allows adding new urls (well, not trought the website).

I would suggest to either remove the suggestion on the [CreatePackages](https://github.com/chocolatey/choco/wiki/CreatePackages#package-icon-guidelines), or change it to use a different provider (in this case, I suggest jsdelivr).

I'm willing to open a PR to change it to jsdelivr, if acceptable.

**NOTE:** Originally reported over at https://github.com/chocolatey/choco/issues/1682

### PR DESCRIPTION
**Pull request by pauby**
Remove rawgit recommendation for icon URL's and make alternative suggestions.

Closes #106.

### CODE REVIEW

**Comment by gep13** [comment]
@pauby your changes have been merged, thanks for your contribution 👍

**Comment by gep13** [comment]
@designxsteph I "think" a similar change might be required in the courses section of the new re-design.

**Comment by designxsteph** [comment]
@gep13 thanks for the heads up, I have updated this!

**Comment by FranklinYu** [comment]
Do we need `https://` prefix for those external links?

**Comment by FranklinYu** [comment]
Ok it turned out that we *do need* those prefixes. It’s [not working](https://chocolatey.org/docs/create-packages#package-icon-guidelines) without them.

**Comment by gep13** [comment]
@FranklinYu thanks for pointing this out.  I have fixed those URL's.

@designxsteph depending on where you put this content in the Modules section of the site, you might need to also fully qualify the URL's.  Let me know if you have any questions.

**Pull request merged**
