### PR TITLE
Add `cmd` example with note about spaces

### PR DESCRIPTION
**Pull request by dragon788**
This could be a separate Example 5 as well.

### CODE REVIEW

**Comment by ferventcoder** [comment]
This is autogenerated from the choco codebase - you probably missed the note at the very bottom of the file.

**Comment by dragon788** [comment]
Every single time...

**Comment by ferventcoder** [comment]
Totally need to move something to the top of the file.

**Comment by ferventcoder** [comment]
Pushed to the top of the file as well as a comment. You will see that on next load out.

**Comment by dragon788** [comment]
Moved this over to https://github.com/chocolatey/choco/pull/1068 .

**Pull request closed without merging**
