### PR TITLE
(#222) Add FAQ entry for semi-connected setups

### LINKED ISSUE #222: [CCM 4.0.0] Add documentation for semi-connected environments
We could use (at least) an FAQ entry around how to configure CCM deployments to handle semi-connected environments in CCM v4.0.0

## Internal issue

[Gitlab](https://gitlab.com/chocolatey/choco-licensed-management-ui/-/issues/493)

### PR DESCRIPTION
**Pull request by vexx32**
Added a FAQ entry detailing the use of MachineContactTimeout and ExecutionTimeout values in deployment steps for semi-connected environments.

Fix #222

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@vexx32 this looks good to me.  We should wait until nearer the release before getting this merged in though, so I won't merge this just yet.

**Review by ferventcoder — APPROVED** [review]
👍

**Review by ferventcoder — APPROVED** [review]

**Comment by ferventcoder** [comment]
This mentions v0.4.0, so I'm okay to merge. Folks most likely won't even see it.

**Pull request merged**
