### PR TITLE
Add hazel server hosting software to How-To-Host-Feed.md

### PR DESCRIPTION
**Pull request by Drakulix**
Hey there chocolatey team,
the organisation I am working and developing for - the Max-Planck Institute for Human Development - just released our own In-House Chocolatey Gallery Software `Hazel` to the public. It would be nice, if you may add it to your list of alternative hosting solutions.

I have not compared Hazel to Nuget.Java.Server, TeamCity or JNuGet, so I do not know, if the Note below may need to be updated to reflect this new addition.

Thanks!

### CODE REVIEW

**Comment by ferventcoder** [comment]
@Drakulix in Rust! Awesome. I will definitely add this. I just added a PHP NuGet server around this same area, so let's push that up first and see if we need to address any merge conflicts.

**Comment by ferventcoder** [comment]
looks like it does, but I will take those and update it.

**Comment by ferventcoder** [comment]
Merged in at 0bfe852609736bd8a808b1d01dd0743002dc97a1

**Comment by Drakulix** [comment]
Thanks!

**Comment by ferventcoder** [comment]
@Drakulix you will see this up on the website (https://chocolatey.org/docs) later today. But it is now like at the wiki.

**Pull request closed without merging**
